name: Alexander Safatli
description: Software Engineer; Masters Graduate
paginate: 10
author: Alexander Safatli
permalink: /:year/:title/
plugins:
    - jekyll-minifier
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
